### ISSUE TITLE
App gives error during detach procedure (KernelSU)

### ISSUE THREAD

**Issue by kgursu** [j-hc/zygisk-detach-app#3]
On KernelSU, with the latest Zygisk-detach Magisk module, the app could not complete the detach procedure, shows an error and as a result, those apps list is lost and procedure not completed at all.
Here are some related screenshots:
[Screenshot_20240328-170324_1.png](https://github.com/j-hc/zygisk-detach-app/assets/35314872/506493c5-a6a7-40b1-844d-ecc5c8d2a80c)

[Screenshot_20240328-170810_1.png](https://github.com/j-hc/zygisk-detach-app/assets/35314872/4f12ca09-5a40-4974-8828-8aa867ebac0c)

[Screenshot_20240328-170403_1.png](https://github.com/j-hc/zygisk-detach-app/assets/35314872/7006c271-d2b5-431d-acc8-6a54bff5f374)

I have a screen record session to clarify things. I may send it anywhere suitable.

Developer zyhk has created a module, which I'm using. Could this create any issues?
[Screenshot_20240328-170247_1.png](https://github.com/j-hc/zygisk-detach-app/assets/35314872/c65ea72c-8291-440d-8df7-8ea4765c4e13)

Here is the latest bootlog:
![bootlog-2024-03-28-16-02-50.tar.gz](https://github.com/j-hc/zygisk-detach-app/files/14791057/bootlog-2024-03-28-16-02-50.tar.gz)

**Comment by j-hc** [comment]
what is the error?

**Comment by kgursu** [comment]
![2024-03-28-18-52-33-723_1.jpg](https://github.com/j-hc/zygisk-detach-app/assets/35314872/4d7e375d-9681-41c9-a0b1-58654f38990b)

**Comment by j-hc** [comment]
does "detach" cli work in termux?: `su -c detach`

and what is the output of this command: `su -c ls -Zla /data/adb/modules/zygisk-detach`

**Comment by kgursu** [comment]
Sorry for the occupation. The cunprit was the module I mentioned. Newly updated one solved this issue.

**Comment by kgursu** [comment]
> does "detach" cli work in termux?: `su -c detach`
> 
> and what is the output of this command: `su -c ls -Zla /data/adb/modules/zygisk-detach`
> 

The same error reoccurred. I want to reopen this issue.
I use Termius, if that changes anything and the detach seems to be working.

The output of the mentioned command is:

su -c detach
zygisk-detach cli by github.com/j-hc
u -c ls -Zla /data/adb/modules/zygisk-detach                                  <
total 32
drwxr-xr-x  4 root root u:object_r:system_file:s0  4096 2024-03-28 19:05 .
drwxr-xr-x 22 root root u:object_r:system_file:s0  4096 2024-03-30 07:01 ..
-rw-------  1 root root u:object_r:system_file:s0    52 2024-03-28 19:05 detach.bin
-rw-r--r--  1 root root u:object_r:system_file:s0   214 2024-03-28 15:59 module.prop
-rw-r--r--  1 root root u:object_r:system_file:s0    97 2024-03-28 15:59 post-fs-data.sh
-rw-r--r--  1 root root u:object_r:system_file:s0   145 2024-03-28 15:59 service.sh
drwxr-xr-x  3 root root u:object_r:system_file:s0  4096 2024-03-28 15:59 system
drwxr-xr-x  2 root root u:object_r:system_file:s0  4096 2024-03-28 15:59 zygisk
